### ISSUE TITLE
How to run the code ? [Solved]

### ISSUE THREAD

**Issue by 3dw1nz0n3** [JingShing/ImageAI-4chan-lowvram-ver#1]
Hi 

Might I know how this code work , is it just running the file gtx16-gpu-run/6g-vram-run ?

As I am running the file , my PC show that no path had been found , while py 3 had been added to patch already.

Might I know how this lowvram ver work ?

Super thanks for your help

**Comment by JingShing** [comment]
Use the right bat file to run the AI. I had set up all the module and environment you need. It only need your computer has installed python and the script can find the path of your python. You may need to check if your python installed has some problem or maybe re-download my low vram ver novelAI.

**Comment by 3dw1nz0n3** [comment]
Thanks for your respond.

Not sure why it still didn't work ,let me try something tomorrow.

Appreciate your hard work on this lower VRAM requirement verion.

**Comment by 3dw1nz0n3** [comment]
I had successfully run the stable-diffusion-webui with the cmd key :--precision full --no-half

It is fun to play with it thanks for your help.
