### ISSUE TITLE
Colab Version got taken down

### ISSUE THREAD

**Issue by melnation-com** [JingShing/ImageAI-4chan-lowvram-ver#8]
Anyone got the saved code?
![image](https://user-images.githubusercontent.com/28845316/203183302-7f0c1a49-0423-4ea8-baa0-a7c11ffa2458.png)
https://snipboard.io/1Nav6k.jpg

**Comment by JingShing** [comment]
Due to DMCA and NovelAI. I can't provide novelai script anymore. You can see this video and get help : https://youtu.be/TyIL7XjMUaw
